name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      VITE_apiKey: '${{ secrets.VITE_apiKey }}'
      VITE_authDomain: '${{ secrets.VITE_authDomain }}'
      VITE_databaseURL: '${{ secrets.VITE_databaseURL }}'
      VITE_projectId: '${{ secrets.VITE_projectId }}'
      VITE_storageBucket: '${{ secrets.VITE_storageBucket }}'
      VITE_messagingSenderId: '${{ secrets.VITE_messagingSenderId }}'
      VITE_appId: '${{ secrets.VITE_appId }}'
      VITE_measurementId: '${{ secrets.VITE_measurementId }}'

    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DISPLAYS_7AC24 }}'
          channelId: live
          projectId: displays-7ac24
